name: test
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  bloc: ^8.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.9
  meta: ^1.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 
  flutter_lints: ^3.0.0







flutter:

  
  uses-material-design: true

  assets:
    - assests/
    - assests/splash_animation/

 